CREATE TABLE AGRI_DATA (
    "YEAR" INT,
    "STATE_NAME" VARCHAR(100),
    "DIST_NAME" VARCHAR(100),
    "RICE_AREA_1000_HA" FLOAT,
    "RICE_PRODUCTION_1000_TONS" FLOAT,
    "RICE_YIELD_TON_HA" FLOAT,
    "WHEAT_AREA_1000_HA" FLOAT,
    "WHEAT_PRODUCTION_1000_TONS" FLOAT,
    "WHEAT_YIELD_TON_HA" FLOAT,
    "KHARIF_SORGHUM_AREA_1000_HA" FLOAT,
    "KHARIF_SORGHUM_PRODUCTION_1000_TONS" FLOAT,
    "KHARIF_SORGHUM_YIELD_TON_HA" FLOAT,
    "RABI_SORGHUM_AREA_1000_HA" FLOAT,
    "RABI_SORGHUM_PRODUCTION_1000_TONS" FLOAT,
    "RABI_SORGHUM_YIELD_TON_HA" FLOAT,
    "SORGHUM_AREA_1000_HA" FLOAT,
    "SORGHUM_PRODUCTION_1000_TONS" FLOAT,
    "SORGHUM_YIELD_TON_HA" FLOAT,
    "PEARL_MILLET_AREA_1000_HA" FLOAT,
    "PEARL_MILLET_PRODUCTION_1000_TONS" FLOAT,
    "PEARL_MILLET_YIELD_TON_HA" FLOAT,
    "MAIZE_AREA_1000_HA" FLOAT,
    "MAIZE_PRODUCTION_1000_TONS" FLOAT,
    "MAIZE_YIELD_TON_HA" FLOAT,
    "FINGER_MILLET_AREA_1000_HA" FLOAT,
    "FINGER_MILLET_PRODUCTION_1000_TONS" FLOAT,
    "FINGER_MILLET_YIELD_TON_HA" FLOAT,
    "BARLEY_AREA_1000_HA" FLOAT,
    "BARLEY_PRODUCTION_1000_TONS" FLOAT,
    "BARLEY_YIELD_TON_HA" FLOAT,
    "CHICKPEA_AREA_1000_HA" FLOAT,
    "CHICKPEA_PRODUCTION_1000_TONS" FLOAT,
    "CHICKPEA_YIELD_TON_HA" FLOAT,
    "PIGEONPEA_AREA_1000_HA" FLOAT,
    "PIGEONPEA_PRODUCTION_1000_TONS" FLOAT,
    "PIGEONPEA_YIELD_TON_HA" FLOAT,
    "MINOR_PULSES_AREA_1000_HA" FLOAT,
    "MINOR_PULSES_PRODUCTION_1000_TONS" FLOAT,
    "MINOR_PULSES_YIELD_TON_HA" FLOAT,
    "GROUNDNUT_AREA_1000_HA" FLOAT,
    "GROUNDNUT_PRODUCTION_1000_TONS" FLOAT,
    "GROUNDNUT_YIELD_TON_HA" FLOAT,
    "SESAMUM_AREA_1000_HA" FLOAT,
    "SESAMUM_PRODUCTION_1000_TONS" FLOAT,
    "SESAMUM_YIELD_TON_HA" FLOAT,
    "RAPESEED_AND_MUSTARD_AREA_1000_HA" FLOAT,
    "RAPESEED_AND_MUSTARD_PRODUCTION_1000_TONS" FLOAT,
    "RAPESEED_AND_MUSTARD_YIELD_TON_HA" FLOAT,
    "SAFFLOWER_AREA_1000_HA" FLOAT,
    "SAFFLOWER_PRODUCTION_1000_TONS" FLOAT,
    "SAFFLOWER_YIELD_TON_HA" FLOAT,
    "CASTOR_AREA_1000_HA" FLOAT,
    "CASTOR_PRODUCTION_1000_TONS" FLOAT,
    "CASTOR_YIELD_TON_HA" FLOAT,
    "LINSEED_AREA_1000_HA" FLOAT,
    "LINSEED_PRODUCTION_1000_TONS" FLOAT,
    "LINSEED_YIELD_TON_HA" FLOAT,
    "SUNFLOWER_AREA_1000_HA" FLOAT,
    "SUNFLOWER_PRODUCTION_1000_TONS" FLOAT,
    "SUNFLOWER_YIELD_TON_HA" FLOAT,
    "SOYABEAN_AREA_1000_HA" FLOAT,
    "SOYABEAN_PRODUCTION_1000_TONS" FLOAT,
    "SOYABEAN_YIELD_TON_HA" FLOAT,
    "OILSEEDS_AREA_1000_HA" FLOAT,
    "OILSEEDS_PRODUCTION_1000_TONS" FLOAT,
    "OILSEEDS_YIELD_TON_HA" FLOAT,
    "SUGARCANE_AREA_1000_HA" FLOAT,
    "SUGARCANE_PRODUCTION_1000_TONS" FLOAT,
    "SUGARCANE_YIELD_TON_HA" FLOAT,
    "COTTON_AREA_1000_HA" FLOAT,
    "COTTON_PRODUCTION_1000_TONS" FLOAT,
    "COTTON_YIELD_TON_HA" FLOAT,
    "FRUITS_AREA_1000_HA" FLOAT,
    "VEGETABLES_AREA_1000_HA" FLOAT,
    "FRUITS_AND_VEGETABLES_AREA_1000_HA" FLOAT,
    "POTATOES_AREA_1000_HA" FLOAT,
    "ONION_AREA_1000_HA" FLOAT,
    "FODDER_AREA_1000_HA" FLOAT
);

select * from  Agri_data

copy Agri_data from 'D:\guvi project 2\cleaned_icrisat_final.csv' delimiter ',' csv header

--1.Year-wise Trend of Rice Production Across States (Top 3)
SELECT "YEAR", "STATE_NAME", SUM("RICE_PRODUCTION_1000_TONS") AS total_rice
FROM AGRI_DATA
GROUP BY "YEAR", "STATE_NAME"
ORDER BY total_rice DESC

--2.Top 5 Districts by Wheat Yield Increase Over the Last 5 Years

SELECT "DIST_NAME",
       MAX("WHEAT_YIELD_TON_HA") - MIN("WHEAT_YIELD_TON_HA") AS yield_increase
FROM AGRI_DATA
WHERE "YEAR" >= (SELECT MAX("YEAR") FROM AGRI_DATA) - 5
GROUP BY "DIST_NAME"
ORDER BY yield_increase DESC
LIMIT 5;

--3.States with the Highest Growth in Oilseed Production (5-Year Growth Rate)

SELECT "STATE_NAME",
       (MAX("OILSEEDS_PRODUCTION_1000_TONS") - MIN("OILSEEDS_PRODUCTION_1000_TONS")) / 
       NULLIF(MIN("OILSEEDS_PRODUCTION_1000_TONS"), 0) AS growth_rate
FROM AGRI_DATA
WHERE "YEAR" >= (SELECT MAX("YEAR") FROM AGRI_DATA) - 5
GROUP BY "STATE_NAME"
ORDER BY growth_rate DESC
LIMIT 5;

--4.District-wise Correlation Between Area and Production for Major Crops (Rice, Wheat, and Maize)

SELECT "DIST_NAME", "YEAR",
       "RICE_AREA_1000_HA", "RICE_PRODUCTION_1000_TONS",
       "WHEAT_AREA_1000_HA", "WHEAT_PRODUCTION_1000_TONS",
       "MAIZE_AREA_1000_HA", "MAIZE_PRODUCTION_1000_TONS"
FROM AGRI_DATA;

--5.Yearly Production Growth of Cotton in Top 5 Cotton Producing States

SELECT "YEAR", "STATE_NAME", SUM("COTTON_PRODUCTION_1000_TONS") AS total_cotton
FROM AGRI_DATA
WHERE "STATE_NAME" IN (
    SELECT "STATE_NAME"
    FROM AGRI_DATA
    GROUP BY "STATE_NAME"
    ORDER BY SUM("COTTON_PRODUCTION_1000_TONS") DESC
    LIMIT 5
)
GROUP BY "YEAR", "STATE_NAME"
ORDER BY "YEAR", "STATE_NAME";

--6.Districts with the Highest Groundnut Production in 2020

SELECT "DIST_NAME", "STATE_NAME", "GROUNDNUT_PRODUCTION_1000_TONS"
FROM AGRI_DATA
WHERE "YEAR" = 2020
ORDER BY "GROUNDNUT_PRODUCTION_1000_TONS" DESC
LIMIT 10;

--7.Annual Average Maize Yield Across All States
SELECT "YEAR",
       ROUND(AVG("MAIZE_YIELD_TON_HA")::NUMERIC, 2) AS avg_maize_yield
FROM AGRI_DATA
GROUP BY "YEAR"
ORDER BY "YEAR";

--8.Total Area Cultivated for Oilseeds in Each State

SELECT "STATE_NAME", SUM("OILSEEDS_AREA_1000_HA") AS total_oilseeds_area
FROM AGRI_DATA
GROUP BY "STATE_NAME"
ORDER BY total_oilseeds_area DESC;


--9.Districts with the Highest Rice Yield

SELECT "DIST_NAME", "STATE_NAME", MAX("RICE_YIELD_TON_HA") AS max_yield
FROM AGRI_DATA
GROUP BY "DIST_NAME", "STATE_NAME"
ORDER BY max_yield DESC
LIMIT 10;

--10.Compare the Production of Wheat and Rice for the Top 5 States Over 10 Years

SELECT "YEAR", "STATE_NAME",
       SUM("RICE_PRODUCTION_1000_TONS") AS rice_prod,
       SUM("WHEAT_PRODUCTION_1000_TONS") AS wheat_prod
FROM AGRI_DATA
WHERE "STATE_NAME" IN (
    SELECT "STATE_NAME"
    FROM AGRI_DATA
    GROUP BY "STATE_NAME"
    ORDER BY SUM("RICE_PRODUCTION_1000_TONS" + "WHEAT_PRODUCTION_1000_TONS") DESC
    LIMIT 5
)
AND "YEAR" >= (SELECT MAX("YEAR") FROM AGRI_DATA) - 10
GROUP BY "YEAR", "STATE_NAME"
ORDER BY "YEAR", "STATE_NAME";








